name: Development

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Build and Test
        run: |
          dotnet build
          dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.coverage.opencover.reportsPaths=**/tweet-service.tests/coverage.xml
            -Dsonar.cs.opencover.reportsPaths=**/tweet-service.tests/coverage.xml
        
        
          
