name: Development

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Install Sonar global tool
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Begin sonar scan
        run: dotnet sonarscanner begin /k:"Kwebbel-project_tweet-service" /o:"kwebbel-project"  /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.cs.opencover.reportsPaths="tweet-service.tests/coverage.xml" /d:sonar.tests="tweet-service.tests" /d:sonar.sources="src" sonar.exclusions="src/Data/MongoDBSettings.cs" /d:sonar.verbose=true 
          
      - name: Build project
        run: |
          dotnet restore
          dotnet build
        
      - name: Build and run unit tests
        run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -o="coverage.xml"
          
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
        
        
          
