name: Development

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Install Coverlet tool
        run: dotnet tool install --global coverlet.console
        
      - name: Install Sonar global tool
        run: dotnet tool install --global dotnet-sonarscanner
          
      - name: Run Sonarscanner
        run: |
          cd src
          dotnet sonarscanner begin /k:"Kwebbel-project_tweet-service" /o:"kwebbel-project" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.cs.opencover.reportsPaths=coverage.xml
          dotnet build --no-incremental
          coverlet .\tweet-service.Tests\bin\Debug\net7.0\tweet-service.Tests.dll -target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
          dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
          
